---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewRestService"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "34d3b28"
  parameters:
    - "description": ""a big city""

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "PrepareTravisBuildFiles"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.22"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "29e6449"
  parameters:
    - "project": "london"
    - "encryptedGithubToken": "H**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryToken": "H**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="
    - "encryptedDockerRegistryUser": "K**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************="

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "ChangePortNumber"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "f8bea4a*"
  parameters:
    - "before": "8080"
    - "after": "8091"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "ChangePortNumber"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.4"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "f8bea4a*"
  parameters:
    - "before": "8080"
    - "after": "8091"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddRestEndpoint"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "caa346c"
  parameters:
    - "returnedClass": "SurveyResultResponse"
    - "fieldName": "results"
    - "fieldType": "List<AggregateResult>"
    - "repo": "london"
    - "handle": "{}"
    - "__mappedParameters": "{"0":{"localKey":"repo","foreignKey":"atomist://github/repository"}}"
    - "__parameters": "{"0":{"displayName":"Java return type","description":"type the endpoint will return","pattern":"@java_class","validInput":"Java class name like ThunderCougarFalconBird","minLength":1,"maxLength":100,"name":"returnedClass","decorated":true},"1":{"displayName":"pojo field name","description":"name of a field in your pojo, blank for none (or not a new pojo)","pattern":"@java_identifier","validInput":"Java identifier","minLength":1,"maxLength":100,"name":"fieldName","decorated":true},"2":{"displayName":"pojo field type","description":"type of that field in your pojo, blank for none (or not a new pojo)","pattern":"@any","validInput":"Java type","minLength":1,"maxLength":100,"name":"fieldType","decorated":true}}"
    - "__intent": "{"0":"add endpoint"}"
    - "__tags": "{"0":"satellite-of-love","1":"rest"}"
    - "__name": "AddRestEndpointPlease"
    - "__description": "run an editor to add a REST endpoint to this project"
    - "__kind": "command-handler"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "RestrictCORS"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.9"
  origin:
    repo: "git@github.com:satellite-of-love/workflow-rugs"
    branch: "master"
    sha: "5d3e90e"

