dist: trusty
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
install: true
script: docker login -u $ATOMIST_REPO_USER -p $ATOMIST_REPO_TOKEN $ATOMIST_DOCKER_REGISTRY
  && bash src/main/scripts/travis-build.bash
env:
  global:
  - secure: CRSayU/n0oTXNsNYpLiXIapcPJxZSdmjMFSRU/dZkw9wghzaiFP7iatIUh5ralSWGmAxpPBfzrnh12ao250ZXRJvCW10EUXKSiEPDyFnd8xEcvccqTqlq/quR31X9endX3j8YWXVmbX8fV49Y49Ucdxg7cYP5ADYV1YiJv1lWIVml2sI05k01oi5i+69LSolXZDT5Ct2mRAk5SetifuwU5VrrQV9fKUXEiHMhzLTM4n6ujjHES7KHB1GwF65dddsQjO5Ov+9pUr4G+IPq0wN9IhgpYKFhtNGWFsiP8//SiItOTRVaagYIKk2ILs0mdw5A3gMy3wvjG6vhjto1J6NM6BmW9DKQHHRgTisPooMFRVbdWDUzgkuzfvfIBk5dVGS6xLwTv89ecz2/+YVFN8mhodEU5TFZNwj76ol84IekPJlJLhA4B4QLw2IsApE5Jp/GEOc9gZAPSttU1QxDr8rolSRRn00tMIpkJh+j2sTIMKyxkbfQihz/tc42ftqtWCEXS9sMkW4QgkffEQmHZnnJ+bU59ZjKZbX5KMH0jybDF0euQcKdGJRRrQ60dnDnze3PJqs/C7yU8jbdYNYTTeCFIwuIcE2NqbCfrlRpGz7lMr0d19DXjljSZ5z+xEqq0oaUbUHkmDKp24mKYPpObvAlkMNYVkyhwT174i/17Xgu94=
  - secure: KNlLWvLIQ5U2sOtDlP0eZDnfYf6GVtUzMikziYL8UYpN4lYHOsdwGnJxC+4mpIlwVdAsSbsHLtRjIHJPymsbKywFLKtOaceylXy7iBu0jTirPQnLslQdxiJ1JQxylTvzfcRljvA8E5h9zGMaWF5JwFq+VdeBJXB2U/3pNXxrCRW6PlYzDgBJmS4/gW4Y3xGzvKv+ATkcKqmDpdArFSUkizfA8NKYdqTPzfPYydZ7H2T0ebySeDqCRv9EP0h7zgjNs137A57cyp33q80MKGWv8V3RuYZ1xi3+4YvuufTQ9xyCnloTks2nNyZvpM5oJQq5CcVwl+0CdkSeGIpDqu9vm9O94EfDVnq+bAS8F0CCgtVNYK7Tyq1LgwkD1NG4kNwjGTgjIEDlEqgUsXehF8qlYWowSLXymN69eNiBTcuelXtoFwpsy3nHXmOtjvzmPbTu6/UYq6ZghYtG9kvgTDKtpDG0gWnMKVw4NaKJDxs3/wkSztI7nv1I+wgxeZAfR7HRcseqTLMNq6jj/F+oapTdT8Yd8Dp2yiu6tZjzBOHfFPIYV8l/8K2MTFESwryeBun3rs2LKlmlkaDc7x8KxVkbrErYWLT+Y5X+uxMtknoTfB7UDV4nYLyE4nUt82H5+PI6IUib8fjnJRSwUP1SpKiAP0Tv3cua4O+7sreSSYaFfSY=
  - ATOMIST_DOCKER_REGISTRY=sforzando-docker-dockerv2-local.artifactoryonline.com
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
